server:
  port: 10040
  tomcat:
    uri-encoding: UTF-8

spring:
  profiles:
    active: dev


---
spring:
  profiles: dev
  datasource:
    name: test
    url: jdbc:mysql://192.168.99.100:3307/my_mall
    username: root
    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 5000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQueryTimeout: 60
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
mybatis:
  #默认扫描resource下的xml文件
  mapper-locations: classpath:mapping/*.xml
  #启用别名的包
  type-aliases-package: com.winter.model
  #经典的数据库命名和Java的驼峰命名匹配
  configuration:
    map-underscore-to-camel-case: true
  ​
#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql